security:
  oauth2:
    client:
      clientId: 341661319536993
      clientSecret: b12bfe499dba5e3c51f9817f03213b77
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me